### ISSUE TITLE
Are you saying that 3.3.2 isn't intended to talk about programmatic association?

### ISSUE THREAD

**Issue by anevins12** [patrickhlauke/wcag-interpretation#2]
When you mentioned that 3.3.2 doesn't mandate the use of the `<label>`, are you implicitly saying that programmatic association in general is not intended by this success criterion? And there are other more relevant criteria? 

Or was this specifically that programmatic `<label>` elements are not mandated for this criterion?

**Comment by patrickhlauke** [comment]
https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html

> This Success Criterion does not require that labels or instructions be correctly marked up, identified, or associated with their respective controls - this aspect is covered separately by [1.3.1: Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships). It is possible for content to pass this Success Criterion (providing relevant labels and instructions) while failing Success Criterion 1.3.1 (if the labels or instructions aren't correctly marked up, identified, or associated).
>
> Further, this Success Criterion does not take into consideration whether or not alternative methods of providing an accessible name or description for form controls and inputs has been used - this aspect is covered separately by [4.1.2: Name, Role and Value](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value). It is possible for controls and inputs to have an appropriate accessible name or description (e.g. using aria-label="...") and therefore pass Success Criterion 4.1.2, but to still fail this Success Criterion (if the labels or instructions aren't presented to all users, not just those using assistive technologies).
